### PR TITLE
changed navbar placement to fixed on top

### PR DESCRIPTION
**Pull request by sanjan**

### CODE REVIEW

**Comment by sanjan** [comment]
@iamigo  can you help to review and merge this. thanks

**Comment by sanjan** [comment]
@iamigo @jgraff2  Thanks. I have updated the release version, release notes and the distro file as requested.

**Comment by sanjan** [comment]
@iamigo I have added a top margin of 50px to multi table container. please check.

**Comment by iamigo** [comment]
The zip file in the PR does not appear to have the extra changes you just added. Please update the zip file and increment the version to 1.1.2 so that I can install it cleanly.

**Pull request closed without merging**
