### PR TITLE
Add tests for SubjectGroups

### PR DESCRIPTION
**Pull request by iamigo**
- getParentGroupForAbsolutePath
- groupName
- getPanelsToDraw

### CODE REVIEW

**Comment by harshkothari410** [comment]
Is there any need of adding such a huge json file ? @iamigo

**Comment by iamigo** [comment]
@harshkothari410 - there is no "need" per se, but it doesn't really cost anything here, and using the one from /public saved me from trying to generate one myself.

**Comment by harshkothari410** [comment]
Because its huge file taking lots of space thats why. I do not have any other concern.

**Comment by harshkothari410** [comment]
Rest of the things looks good for me.

**Comment by iamigo** [comment]
If file space is a concern I can construct a smaller hierarchy for the purpose of testing.

**Comment by harshkothari410** [comment]
That would be good. Because this is 4.8 MB of file

**Comment by iamigo** [comment]
ok made test hierarchy smaller

**Pull request merged**
